export const SET_SEARCH_STRING = "SET_SEARCH_STRING";
export const FETCH_WEATHER_FORECAST = "FETCH_WEATHER_FORECAST";
export const WEATHER_FORECATS_REQUEST = "WEATHER_FORECATS_REQUEST";
export const WEATHER_FORECATS_RESPONSE = "WEATHER_FORECATS_RESPONSE";
export const WEATHER_FORECATS_ERROR = "WEATHER_FORECATS_ERROR";
